# sudo: required
# language: generic 
# services:
#     - docker

# before_install:
#     - docker build -t cruzee/docker-fibo-app -f ./client/Dockerfile.dev ./client

# script:
#     - docker run -e CI=true cruzee/docker-fibo-app npm run test

# after_success:
#     - docker build -t cruzee/docker-fibo-app-client ./client
#     - docker build -t cruzee/docker-fibo-app-nginx ./nginx
#     - docker build -t cruzee/docker-fibo-app-server ./server
#     - docker build -t cruzee/docker-fibo-app-worker ./worker
#     # Login to Docker CLI
#     - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#     # Push image to DockerHub
#     - docker push cruzee/docker-fibo-app-client
#     - docker push cruzee/docker-fibo-app-nginx
#     - docker push cruzee/docker-fibo-app-server
#     - docker push cruzee/docker-fibo-app-worker

# deploy:
#     provider: elasticbeanstalk
#     region: "us-east-2"
#     app: "docker-fibo-app"
#     env: "DockerFiboApp-env"
#     bucket_name: "elasticbeanstalk-us-east-2-387202753299"
#     bucket_path: "docker-fibo-app"
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY