sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t cruzee/ui-app-test -f ./innov8-interviewer-ui/Dockerfile.dev ./innov8-interviewer-ui
#    - docker build -t cruzee/api-app-test -f ./innov8-interviewer-api/Dockerfile.dev ./innov8-interviewer-api

script:
    - docker run -e CI=true cruzee/ui-app-test npm run test

after_success:
    - docker build -t cruzee/innov8-interviewer-ui ./innov8-interviewer-ui
    - docker build -t cruzee/innov8-interviewer-api ./innov8-interviewer-api
    - docker build -t cruzee/innov8-interviewer-nginx ./innov8-interviewer-nginx
    # Login to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push image to DockerHub
    - docker push cruzee/innov8-interviewer-ui
    - docker push cruzee/innov8-interviewer-api
    - docker push cruzee/innov8-interviewer-nginx

deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-1"
    app: "innov8-interviewer-app-1"
    env: "Innov8InterviewerApp1-env"
    bucket_name: "usaa-interviewer-app"
    bucket_path: "innov8-interviewer-app"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY