version: '3'
services:

    mysql-database:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mysql_password
            MYSQL_DATABASE: usaa_interviewer_app
        ports:
          - 3306:3306
          
    mongo-db:
        image: mongo
        restart: always
        environment:
            MONGO_DB_ROOT_USERNAME: root-user
            MONGO_DB_ROOT_PASSWORD: mongodb_password
        ports: 
            - 27017:27017
    
    adminer:
        image: adminer
        restart: always
        ports:
          - 7000:8080

    mongo-express:
        image: mongo-express
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo-db
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: root-user
            ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb_password
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: pass
        depends_on:
            - mongo-db
        ports:
            - "8888:8081"
          
    interviewer-api:
        depends_on:
            - mysql-database
        build: 
            dockerfile: Dockerfile.dev
            context: ./innov8-interviewer-api
        ports:
          - 8080:8080
        environment:
            - MYSQL_URL=jdbc:mysql://mysql-database:3306/usaa_interviewer_app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
            - MYSQL_USERNAME=root
            - MYSQL_PASSWORD=mysql_password

    requirement-api:
        depends_on:
            - mongo-db
        build: 
            dockerfile: Dockerfile.dev
            context: ./innov8-requirement-api
        volumes: 
            - /app/node_modules
            - ./innov8-requirement-api:/app
        ports:
            - 7070:7070
        environment:
            - REQUIREMENT_MONGODB_URL=mongodb://mongo-db:27017/usaa-requirements-app
            - MONGO_DB_ROOT_USERNAME=root-user
            - MONGO_DB_ROOT_PASSWORD=mongodb_password
            - REQ_API_PORT=7070

    contact-api:
        depends_on:
            - mongo-db
        build: 
            dockerfile: Dockerfile.dev
            context: ./innov8-contact-api
        volumes: 
            - /app/node_modules
            - ./innov8-contact-api:/app
        ports:
            - 6060:6060
        environment:
            - CONTACT_MONGODB_URL=mongodb://mongo-db:27017/usaa-requirements-app
            - MONGO_DB_ROOT_USERNAME=root-user
            - MONGO_DB_ROOT_PASSWORD=mongodb_password
            - REQ_API_PORT=6060
    
    interviewer-ui:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./innov8-interviewer-ui
        volumes: 
            - /app/node_modules
            - ./innov8-interviewer-ui:/app
        ports:
            - 3000:3000

    nginx:
        restart: always
        depends_on:
            - interviewer-api
            - interviewer-ui
            - requirement-api
            - contact-api
        build:
            dockerfile: Dockerfile.dev
            context: ./innov8-interviewer-nginx
        volumes:
            - ./innov8-interviewer-nginx/local-cert:/etc/nginx/certs
        ports:
            - 80:80
            - 443:443