version: '3'
services:

    mysql-database:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mysql_password
            MYSQL_DATABASE: usaa_interviewer_app
        ports:
          - 3306:3306
          
    adminer:
        image: adminer
        restart: always
        ports:
          - 7000:8080
          
    interviewer-api:
        depends_on:
            - mysql-database
        build: 
            dockerfile: Dockerfile.dev
            context: ./innov8-interviewer-api
        ports:
          - 8080:8080
        environment:
            - MYSQL_URL=jdbc:mysql://mysql-database:3306/usaa_interviewer_app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
            - MYSQL_USERNAME=root
            - MYSQL_PASSWORD=mysql_password
    
    interviewer-ui:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./innov8-interviewer-ui
        volumes: 
            - /app/node_modules
            - ./innov8-interviewer-ui:/app
        ports:
            - 3000:3000

    nginx:
        restart: always
        depends_on:
            - interviewer-api
            - interviewer-ui
        build:
            dockerfile: Dockerfile.dev
            context: ./innov8-interviewer-nginx
        ports:
            - 80:80